version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: carrental_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: carrental
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: carrental-backend:local
    container_name: carrental_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/carrental
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    restart: unless-stopped

volumes:
  mysql_data:
    name: carrental_mysql_data
